### ISSUE TITLE
error

### ISSUE THREAD

**Issue by thebedrohlich** [Wolftallemo/roblox-follower-purge#1]
im getting this error:

![image](https://user-images.githubusercontent.com/93493358/139601211-02a81e21-66a7-4b25-899e-ef1431739b19.png)

**Comment by Wolftallemo** [comment]
I would suggest changing your password as your authentication cookie and pin are now public. Also the cookie must be wrapped in double quotes `"` (as should the pin), I might make that a bit more obvious.
